INSERT INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (0, 'ROLE_ANONYMOUS');
INSERT INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (1, 'ROLE_ADMIN');
INSERT INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (2, 'ROLE_USER');


INSERT into USERS (ID, PASSWORD, USERNAME, ENABLED)
    VALUES (0, '$2a$10$Em7KE6jS/CEQgzdYpdBqLu4.Q76KCLbhbNl.KwunXEj2Iy3SpjDxS', 'user', true);

